version: "3.5"
services:

  mysql:
    container_name: mysql
    image: mariadb:10.5.5
    env_file:
      - .env
    environment:
      - MYSQL_ROOT_PASSWORD=${DATABASE_PASSWORD}
      - MYSQL_DATABASE=${DATABASE_NAME}
      - MYSQL_USER=${DATABASE_USER}
      - MYSQL_PASSWORD=${DATABASE_PASSWORD}
    ports:
      - "3306:3306"
    networks:
      - myappyo
    volumes:
      - mysqldata:/var/lib/mysql

  redis:
    container_name: redis
    image: redis:6.0.5
    ports:
      - "6379:6379"
    networks:
      - myappyo

volumes:
  mysqldata: {}

networks:
  myappyo:
    driver: bridge
